### ISSUE TITLE
F to C conversion

### ISSUE THREAD

**Issue by tracstarr** [Eric-Gonzalez/nest-dashing-widget#3]
First, there is a small bug in which "input" is used instead of the parameter "temp". However, I would also provide the following suggestion. For those of us that use metric, it would be nice to show the one decimal place that we see on the nest.

def f_to_c(temp)
	r = (((temp.to_f - 32) * 5) / 9)
	return sprintf("%.1f",r)	
end

**Comment by Eric-Gonzalez** [comment]
Thank you for the suggestion. If you open a PR I would be happy to merge it. 

Thanks!

**Comment by Eric-Gonzalez** [comment]
Resolved in #4
